# Generated by Django 6.0.7 on 2026-07-11 13:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_type', models.CharField(choices=[('FIXED', 'ثابت'), ('VARIABLE', 'متغير')], default='VARIABLE', max_length=10)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('ONE_OFF', 'مرة واحدة'), ('DAY', 'يوم'), ('WEEK', 'أسبوع'), ('MONTH', 'شهر'), ('YEAR', 'سنة')], default='ONE_OFF', max_length=10)),
                ('date_incurred', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_incurred', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('COMPLETED', 'منتهي')], default='ACTIVE', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='core.route')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.PositiveIntegerField(default=14)),
                ('instapay_handle', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.route')),
            ],
            options={
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('INSTAPAY', 'إنستاباي')], max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'مدفوع')], default='PENDING', max_length=10)),
                ('ride_status', models.CharField(choices=[('IN_CAR', 'في السيارة'), ('DROPPED_OFF', 'نزل'), ('CANCELLED', 'ملغي')], default='IN_CAR', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='core.ride')),
                ('drop_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_passengers', to='core.routestop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_passengers', to='core.routestop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
